mtnPackages: {
            "1gb": {
              size: "1GB",
              costPrice: 4.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "2gb": {
              size: "2GB",
              costPrice: 8.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "3gb": {
              size: "3GB",
              costPrice: 12.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "4gb": {
              size: "4GB",
              costPrice: 16.7,
              agentPrice: 0.0,
              isActive: true,
            },
            "5gb": {
              size: "5GB",
              costPrice: 20.6,
              agentPrice: 0.0,
              isActive: true,
            },
            "6gb": {
              size: "6GB",
              costPrice: 25.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "7gb": {
              size: "7GB",
              costPrice: 28.7,
              agentPrice: 0.0,
              isActive: true,
            },
            "8gb": {
              size: "8GB",
              costPrice: 33.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "10gb": {
              size: "10GB",
              costPrice: 40.3,
              agentPrice: 0.0,
              isActive: true,
            },
            "15gb": {
              size: "15GB",
              costPrice: 58.3,
              agentPrice: 0.0,
              isActive: true,
            },
            "20gb": {
              size: "20GB",
              costPrice: 78.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "25gb": {
              size: "25GB",
              costPrice: 98.7,
              agentPrice: 0.0,
              isActive: true,
            },
            "30gb": {
              size: "30GB",
              costPrice: 118.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "40gb": {
              size: "40GB",
              costPrice: 154.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "50gb": {
              size: "50GB",
              costPrice: 193.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "100gb": {
              size: "100GB",
              costPrice: 377.0,
              agentPrice: 0.0,
              isActive: true,
            },
          },
          vodafonePackages: {
            "5gb": {
              size: "5GB",
              costPrice: 22.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "10gb": {
              size: "10GB",
              costPrice: 43.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "15gb": {
              size: "15GB",
              costPrice: 59.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "20gb": {
              size: "20GB",
              costPrice: 79.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "25gb": {
              size: "25GB",
              costPrice: 98.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "30gb": {
              size: "30GB",
              costPrice: 115.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "35gb": {
              size: "35GB",
              costPrice: 135.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "40gb": {
              size: "40GB",
              costPrice: 149.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "45gb": {
              size: "45GB",
              costPrice: 172.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "50gb": {
              size: "50GB",
              costPrice: 183.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "100gb": {
              size: "100GB",
              costPrice: 361.0,
              agentPrice: 0.0,
              isActive: true,
            },
          },
          airteltigoPackages: {
            "1gb": {
              size: "1GB",
              costPrice: 4.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "2gb": {
              size: "2GB",
              costPrice: 8.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "3gb": {
              size: "3GB",
              costPrice: 12.5,
              agentPrice: 0.0,
              isActive: true,
            },
            "4gb": {
              size: "4GB",
              costPrice: 16.7,
              agentPrice: 0.0,
              isActive: true,
            },
            "5gb": {
              size: "5GB",
              costPrice: 22.6,
              agentPrice: 0.0,
              isActive: true,
            },
            "6gb": {
              size: "6GB",
              costPrice: 25.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "7gb": {
              size: "7GB",
              costPrice: 29.7,
              agentPrice: 0.0,
              isActive: true,
            },
            "8gb": {
              size: "8GB",
              costPrice: 33.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "10gb": {
              size: "10GB",
              costPrice: 42.3,
              agentPrice: 0.0,
              isActive: true,
            },
            "15gb": {
              size: "15GB",
              costPrice: 46.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "20gb": {
              size: "20GB",
              costPrice: 56.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "25gb": {
              size: "25GB",
              costPrice: 62.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "30gb": {
              size: "30GB",
              costPrice: 67.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "40gb": {
              size: "40GB",
              costPrice: 82.0,
              agentPrice: 0.0,
              isActive: true,
            },
            "50gb": {
              size: "50GB",
              costPrice: 96.0,
              agentPrice: 0.0,
              isActive: true,
            },
          },